# docker-compose for Connect April 2022 demo
# sets up Testbed API and UI services
version: "3.9"
services:
  api:
    image: ga4gh/ga4gh-testbed-api:0.1.0
    hostname: testbed-api.ga4gh.org
    ports:
      - "4500:4500"
  ui:
    image: ga4gh/ga4gh-testbed-ui:0.1.0-connect
    hostname: testbed-ui.ga4gh.org
    ports:
      - "80:80"
